apiVersion: apps/v1
kind: Deployment
metadata:
  name: labproj18-deploy
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExportBack
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        octopusexport: OctopusExportBack
    spec:
      volumes:
        - name: pvc-9ecae6ff-f895-4146-bbfa-d29e520883c6
          persistentVolumeClaim:
            claimName: labproj18-pvc
      containers:
        - name: api
          image: image-registry.openshift-image-registry.svc:5000/labproj18/api:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: TIMEOUT
              value: '3000'
            - name: MAX_WORKERS
              value: '1'
            - name: PORT
              value: '3000'
          imagePullPolicy: Always
          volumeMounts:
            - name: pvc-9ecae6ff-f895-4146-bbfa-d29e520883c6
              mountPath: /db
              subPath: ''
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
