apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: labproj18-pvc

spec:

  accessModes:

    - ReadWriteMany

  volumeMode: Filesystem

  resources:

    requests:

      storage: 2Gi

  storageClassName: managed-nfs-storage
