apiVersion: apps/v1
kind: Deployment
metadata:
  name: labproj18-front-deploy
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExportFront
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        octopusexport: OctopusExportFront
    spec:
      containers:
        - name: front-end
          image: >-
            image-registry.openshift-image-registry.svc:5000/labproj18/front-end:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: lab18proj-front-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
